### ISSUE TITLE
没有开源怎么好意思发上来，丢人

### ISSUE THREAD

**Issue by Russinovich** [basketwill/Z0BPcTools#5]

**Comment by basketwill** [comment]
谁规定github上的东西一定是代码呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Russinovich <notifications@github.com&gt;
发送时间: 2020年7月24日 14:14
收件人: basketwill/Z0BPcTools <Z0BPcTools@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[basketwill/Z0BPcTools] 没有开源怎么好意思发上来，丢人 (#5)





 
没有开源怎么好意思发上来，丢人

**Comment by basketwill** [comment]
> _No description provided._

谁规定了github必须放上去是代码？？
